from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

from app.views import (
    add_review,
    add_to_cart,
    advisor_chat,
    advisor_profile,
    book_create,
    book_delete,
    book_detail,
    book_edit,
    book_list,
    cancel_order,
    checkout,
    delete_cart_item,
    dashboard_view,
    health_check,
    login_view,
    logout_view,
    notifications_view,
    order_detail,
    order_list,
    profile_view,
    register_view,
    role_dashboard_view,
    shipping_detail,
    staff_orders_view,
    staff_shipping_view,
    update_cart_item,
    view_cart,
)


urlpatterns = [
    path("healthz/", health_check, name="health_check"),
    path("", RedirectView.as_view(url="/books/", permanent=False), name="home"),
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("admin/dashboard/", role_dashboard_view, {"role": "admin"}, name="admin_dashboard"),
    path("staff/dashboard/", role_dashboard_view, {"role": "staff"}, name="staff_dashboard"),
    path("customer/dashboard/", role_dashboard_view, {"role": "customer"}, name="customer_dashboard"),
    path("admin/", admin.site.urls),
    path("profile/", profile_view, name="profile"),
    path("advisor/chat/", advisor_chat, name="advisor_chat"),
    path("advisor/profile/", advisor_profile, name="advisor_profile"),
    path("books/", book_list, name="book_list"),
    path("books/create/", book_create, name="book_create"),
    path("books/<int:pk>/", book_detail, name="book_detail"),
    path("books/<int:pk>/edit/", book_edit, name="book_edit"),
    path("books/<int:pk>/delete/", book_delete, name="book_delete"),
    path("books/<int:pk>/review/", add_review, name="add_review"),
    path("cart/<int:customer_id>/", view_cart, name="view_cart"),
    path("cart/add/", add_to_cart, name="add_to_cart"),
    path("cart/<int:customer_id>/update/", update_cart_item, name="update_cart_item"),
    path(
        "cart/<int:customer_id>/delete-item/<int:item_id>/",
        delete_cart_item,
        name="delete_cart_item",
    ),
    path("checkout/", checkout, name="checkout"),
    path("my-orders/", order_list, name="my_orders"),
    path("orders/", order_list, name="order_list"),
    path("orders/<int:pk>/", order_detail, name="order_detail"),
    path("orders/<int:pk>/cancel/", cancel_order, name="cancel_order"),
    path("staff/orders/", staff_orders_view, name="staff_orders"),
    path("staff/shipping/", staff_shipping_view, name="staff_shipping"),
    path("shipping/<int:order_id>/", shipping_detail, name="shipping_detail"),
    path("notifications/", notifications_view, name="notifications"),
]
